service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  getApplicants:
    handler: src/handlers/getApplicants.handler
    events:
      - httpApi:
          path: /applicants
          method: get
          
plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: false